version: '3'
services:
    app:
        container_name: docker-node-postgres
        restart: always
        build: .
        ports:
            - '3000:3000'
        links:
            - postgresql


    postgresql:
        image: postgres:13
        container_name: postgresql
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: terminator_db
